# Header
menu:
  Home: /blog/
  Archives: /archives
rss: /blog/atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: bottom
widgets:
- recent_posts
- twitter
- tagcloud

# Miscellaneous
google_analytics: UA-648525-7
favicon: /favicon.png
twitter: para_io
google_plus:
fb_admins:
fb_app_id: 119564591416126